name: Test Coverage

on: [pull_request]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Run tests
        run: |
          go test -v -coverprofile=profile.cov ./...
          
      - name: Verify coverage
        run: |
          if [ ! -f profile.cov ]; then
            echo "Файл покрытия не создан!"
            exit 1
          fi
          
          COVERAGE=$(go tool cover -func=profile.cov | grep total: | awk '{print $3}' | sed 's/%//')
          echo "Покрытие: ${COVERAGE}%"
          
          if (( $(echo "$COVERAGE < 65" | bc -l) )); then
            echo "Требуется минимум 65%"
            exit 1
          fi