name: Go CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Get dependencies
      run: go mod tidy
      
    - name: Run tests with coverage
      run: |
        go test -coverprofile=coverage.out -covermode=atomic -coverpkg=./... ./...
        go tool cover -func=coverage.out
        
    - name: Verify coverage
      run: |
        COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
        echo "Current coverage: $COVERAGE%"
        if (( $(echo "$COVERAGE < 65" | bc -l) )); then
          echo "Coverage is below 65%"
          exit 1
        else
          echo "Coverage is acceptable"
        fi